# This is a basic workflow to help you get started with Actions

name: Check submodule changes and build Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths: "linux"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Build Linux
        run: |
          ./install-deps.sh;
          SUBMODULE_HEAD_HASH=$(git rev-parse HEAD:linux);
          wget https://github.com/sebastianrcnt/linux/archive/${SUBMODULE_HEAD_HASH}.zip;
          unzip -q $SUBMODULE_HEAD_HASH.zip;
          ./build-linux.sh ./linux-$SUBMODULE_HEAD_HASH tinyconfig;
