name: clean compilation check

on:
  push:
    # only triggered by file update on test folder!
    paths: "test/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Check if is compiled properly
        run: |
          make -C test
